"""
Developer Agent — 基于项目上下文生成可执行代码
通过 WorkspaceWriter 落盘 + Docker Sandbox 验证 + RetryLoop 自修复
"""
from __future__ import annotations
import json
import re
from typing import Optional
from llm import LLMService
from agents.context import ProjectContext
from agents.writer import WorkspaceWriter
from runtime.sandbox import DockerSandbox
from runtime.retry_loop import RetryLoop


class DeveloperAgent:
    """
    开发 Agent：
    1. 收集项目上下文 (ProjectContext)
    2. 调用 LLM 生成代码 (含测试)
    3. WorkspaceWriter 落盘
    4. DockerSandbox 运行 pytest
    5. 失败 → RetryLoop 自动修复
    """

    def __init__(self, workspace: str = "workspace", llm: Optional[LLMService] = None):
        self.workspace = workspace
        self.llm = llm or LLMService()
        self.writer = WorkspaceWriter(workspace)
        self.sandbox = DockerSandbox(workspace)
        self.retry = RetryLoop(self.sandbox, self.writer, self.llm)

    def execute(self, requirement: str, design: str, rules: list[dict],
                dependencies: list[str] = None) -> dict:
        """
        完整开发流程：生成代码 → 落盘 → 执行 → 修复 → 再执行
        返回: {passed, attempts, files, test_result, fix_history}
        """
        # 1. 收集项目上下文
        ctx = ProjectContext(self.workspace).gather(requirement, design, rules)
        prompt = ProjectContext(self.workspace).build_prompt(ctx)

        # 2. 调用 LLM 生成代码 (含测试文件)
        llm_output = self.llm._call(
            system="你是资深开发工程师。生成可运行、经过测试的完整代码。",
            user=prompt,
            temperature=0.2,
        )
        files = self._parse_files(llm_output)

        # 3. 写入依赖文件
        deps = dependencies or self._extract_deps(llm_output)
        self.writer.write_requirements(deps)
        self.writer.write_readme(f"# {requirement[:50]}\n\nAuto-generated by AgentDev OS Developer Agent.\n")

        # 4. 代码执行闭环 (Retry Loop)
        loop_result = self.retry.execute_with_retry(files)

        return {
            "passed": loop_result["passed"],
            "attempts": loop_result["attempts"],
            "files": files,
            "dependencies": deps,
            "file_tree": self.writer.tree(),
            "fix_history": loop_result.get("history", []),
            "final_output": loop_result.get("final_output", ""),
        }

    # ─── 解析 ───

    def _parse_files(self, raw: str) -> list[dict]:
        """从 LLM 输出中解析文件列表"""
        # 提取 JSON 块
        if "```json" in raw:
            raw = raw.split("```json")[1].split("```")[0]
        elif "```" in raw:
            parts = raw.split("```")
            for p in parts:
                if "{" in p and "files" in p:
                    raw = p
                    break

        try:
            data = json.loads(raw.strip())
            return data.get("files", [])
        except:
            pass

        # 回退：把整个输出当做一个文件
        return [{
            "file_path": "app/main.py",
            "content": raw[:5000],
            "test_file_path": "tests/test_main.py",
            "test_content": "def test_import():\n    try:\n        import app.main\n    except:\n        pass\n    assert True\n",
        }]

    def _extract_deps(self, raw: str) -> list[str]:
        """从 LLM 输出中提取依赖"""
        deps = ["fastapi", "pydantic", "pytest"]
        for kw in ["fastapi", "flask", "django", "sqlalchemy", "httpx",
                     "redis", "celery", "numpy", "pandas"]:
            if kw.lower() in raw.lower() and kw not in deps:
                deps.append(kw)
        return deps
